# Generated by Django 2.2.8 on 2019-12-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_first_name', models.CharField(max_length=255)),
                ('owner_last_name', models.CharField(max_length=255)),
                ('address_line_1', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=255)),
            ],
        ),
    ]
